sudo: false
dist: bionic
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

cache: pip

addons:
  apt:
    update: true

install:
  - travis_retry git submodule update --init --recursive
  - ./install.sh

script:
  - ./janus download
  - ./janus build
